// <auto-generated />
using System;
using MealPlannerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MealPlannerAPI.Migrations
{
    [DbContext(typeof(MealPlannerDbContext))]
    [Migration("20260124052058_AddPaymentMethod")]
    partial class AddPaymentMethod
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MealPlannerAPI.Models.ChatHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiResponse")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MealPlanId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatHistories");
                });

            modelBuilder.Entity("MealPlannerAPI.Models.HealthProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Allergies")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DietaryPreferences")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Goals")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HealthConditions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("HealthProfiles");
                });

            modelBuilder.Entity("MealPlannerAPI.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CookTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MealPlanId")
                        .HasColumnType("int");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<int?>("PrepTime")
                        .HasColumnType("int");

                    b.Property<string>("Recipe")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("Servings")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalCalories")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("TotalCarbs")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("TotalFat")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("TotalProtein")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("MealPlannerAPI.Models.MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlanDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserRequest")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("MealPlannerAPI.Models.MealPlanIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsMatched")
                        .HasColumnType("bit");

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("ProductId");

                    b.ToTable("MealPlanIngredients");
                });

            modelBuilder.Entity("MealPlannerAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MealPlanId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReceiverName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MealPlannerAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MealPlannerAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Calories")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("Carbs")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("Fat")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("Fiber")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Keywords")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Protein")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("QuantityInStock")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 165m,
                            Carbs = 0m,
                            Category = "Thịt",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 3.6m,
                            IsAvailable = true,
                            Keywords = "ức gà, chicken breast, thịt gà, gà",
                            Name = "Ức gà CP 500g",
                            Price = 45000m,
                            Protein = 31m,
                            QuantityInStock = 100m,
                            Unit = "gói"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 250m,
                            Carbs = 0m,
                            Category = "Thịt",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 15m,
                            IsAvailable = true,
                            Keywords = "thịt bò, beef, bò",
                            Name = "Thịt bò Úc 500g",
                            Price = 150000m,
                            Protein = 26m,
                            QuantityInStock = 50m,
                            Unit = "gói"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 143m,
                            Carbs = 0m,
                            Category = "Thịt",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 4m,
                            IsAvailable = true,
                            Keywords = "thịt heo, thịt lợn, pork",
                            Name = "Thịt heo nạc vai 500g",
                            Price = 65000m,
                            Protein = 26m,
                            QuantityInStock = 80m,
                            Unit = "gói"
                        },
                        new
                        {
                            Id = 4,
                            Calories = 208m,
                            Carbs = 0m,
                            Category = "Hải sản",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 13m,
                            IsAvailable = true,
                            Keywords = "cá hồi, salmon, cá",
                            Name = "Cá hồi phi lê 300g",
                            Price = 180000m,
                            Protein = 20m,
                            QuantityInStock = 30m,
                            Unit = "gói"
                        },
                        new
                        {
                            Id = 5,
                            Calories = 99m,
                            Carbs = 0m,
                            Category = "Hải sản",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 0.3m,
                            IsAvailable = true,
                            Keywords = "tôm, shrimp, tôm sú",
                            Name = "Tôm sú size 40 500g",
                            Price = 120000m,
                            Protein = 24m,
                            QuantityInStock = 40m,
                            Unit = "gói"
                        },
                        new
                        {
                            Id = 6,
                            Calories = 34m,
                            Carbs = 7m,
                            Category = "Rau củ",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 0.4m,
                            IsAvailable = true,
                            Keywords = "bông cải, broccoli, súp lơ",
                            Name = "Bông cải xanh hữu cơ 300g",
                            Price = 15000m,
                            Protein = 2.8m,
                            QuantityInStock = 100m,
                            Unit = "gói"
                        },
                        new
                        {
                            Id = 7,
                            Calories = 18m,
                            Carbs = 3.9m,
                            Category = "Rau củ",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 0.2m,
                            IsAvailable = true,
                            Keywords = "cà chua, tomato",
                            Name = "Cà chua Đà Lạt 500g",
                            Price = 20000m,
                            Protein = 0.9m,
                            QuantityInStock = 150m,
                            Unit = "gói"
                        },
                        new
                        {
                            Id = 8,
                            Calories = 19m,
                            Carbs = 3m,
                            Category = "Rau củ",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 0.2m,
                            IsAvailable = true,
                            Keywords = "rau muống, morning glory",
                            Name = "Rau muống 300g",
                            Price = 8000m,
                            Protein = 2.6m,
                            QuantityInStock = 200m,
                            Unit = "bó"
                        },
                        new
                        {
                            Id = 9,
                            Calories = 41m,
                            Carbs = 10m,
                            Category = "Rau củ",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 0.2m,
                            IsAvailable = true,
                            Keywords = "cà rốt, carrot",
                            Name = "Cà rốt 500g",
                            Price = 12000m,
                            Protein = 0.9m,
                            QuantityInStock = 120m,
                            Unit = "gói"
                        },
                        new
                        {
                            Id = 10,
                            Calories = 86m,
                            Carbs = 20m,
                            Category = "Rau củ",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 0.1m,
                            IsAvailable = true,
                            Keywords = "khoai lang, sweet potato",
                            Name = "Khoai lang 500g",
                            Price = 18000m,
                            Protein = 1.6m,
                            QuantityInStock = 80m,
                            Unit = "gói"
                        },
                        new
                        {
                            Id = 11,
                            Calories = 26m,
                            Carbs = 6.5m,
                            Category = "Rau củ",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 0.1m,
                            IsAvailable = true,
                            Keywords = "bí đỏ, pumpkin",
                            Name = "Bí đỏ 500g",
                            Price = 15000m,
                            Protein = 1m,
                            QuantityInStock = 60m,
                            Unit = "gói"
                        },
                        new
                        {
                            Id = 12,
                            Calories = 567m,
                            Carbs = 16m,
                            Category = "Hạt",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 49m,
                            IsAvailable = true,
                            Keywords = "đậu phộng, peanut, lạc",
                            Name = "Đậu phộng rang 200g",
                            Price = 25000m,
                            Protein = 26m,
                            QuantityInStock = 100m,
                            Unit = "gói"
                        },
                        new
                        {
                            Id = 13,
                            Calories = 130m,
                            Carbs = 28m,
                            Category = "Tinh bột",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 0.3m,
                            IsAvailable = true,
                            Keywords = "gạo, rice, cơm",
                            Name = "Gạo ST25 5kg",
                            Price = 140000m,
                            Protein = 2.7m,
                            QuantityInStock = 50m,
                            Unit = "bao"
                        },
                        new
                        {
                            Id = 14,
                            Calories = 389m,
                            Carbs = 66m,
                            Category = "Tinh bột",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 7m,
                            IsAvailable = true,
                            Keywords = "yến mạch, oats, oat",
                            Name = "Yến mạch nguyên hạt 500g",
                            Price = 55000m,
                            Protein = 17m,
                            QuantityInStock = 60m,
                            Unit = "gói"
                        },
                        new
                        {
                            Id = 15,
                            Calories = 109m,
                            Carbs = 25m,
                            Category = "Tinh bột",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 0.2m,
                            IsAvailable = true,
                            Keywords = "bún, rice noodle",
                            Name = "Bún gạo 500g",
                            Price = 18000m,
                            Protein = 0.9m,
                            QuantityInStock = 100m,
                            Unit = "gói"
                        },
                        new
                        {
                            Id = 16,
                            Calories = 35m,
                            Carbs = 2m,
                            Category = "Gia vị",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 0m,
                            IsAvailable = true,
                            Keywords = "nước mắm, fish sauce",
                            Name = "Nước mắm Phú Quốc 500ml",
                            Price = 45000m,
                            Protein = 6m,
                            QuantityInStock = 80m,
                            Unit = "chai"
                        },
                        new
                        {
                            Id = 17,
                            Calories = 884m,
                            Carbs = 0m,
                            Category = "Gia vị",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 100m,
                            IsAvailable = true,
                            Keywords = "dầu ăn, cooking oil",
                            Name = "Dầu ăn 1L",
                            Price = 38000m,
                            Protein = 0m,
                            QuantityInStock = 100m,
                            Unit = "chai"
                        },
                        new
                        {
                            Id = 18,
                            Calories = 149m,
                            Carbs = 33m,
                            Category = "Gia vị",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 0.5m,
                            IsAvailable = true,
                            Keywords = "tỏi, garlic",
                            Name = "Tỏi băm 200g",
                            Price = 22000m,
                            Protein = 6.4m,
                            QuantityInStock = 120m,
                            Unit = "hũ"
                        },
                        new
                        {
                            Id = 19,
                            Calories = 80m,
                            Carbs = 18m,
                            Category = "Gia vị",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 0.8m,
                            IsAvailable = true,
                            Keywords = "gừng, ginger",
                            Name = "Gừng tươi 200g",
                            Price = 10000m,
                            Protein = 1.8m,
                            QuantityInStock = 150m,
                            Unit = "gói"
                        },
                        new
                        {
                            Id = 20,
                            Calories = 40m,
                            Carbs = 9m,
                            Category = "Gia vị",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 0.1m,
                            IsAvailable = true,
                            Keywords = "hành tím, shallot",
                            Name = "Hành tím 300g",
                            Price = 15000m,
                            Protein = 1.1m,
                            QuantityInStock = 100m,
                            Unit = "gói"
                        },
                        new
                        {
                            Id = 21,
                            Calories = 155m,
                            Carbs = 1.1m,
                            Category = "Trứng & Sữa",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 11m,
                            IsAvailable = true,
                            Keywords = "trứng, egg, trứng gà",
                            Name = "Trứng gà",
                            Price = 35000m,
                            Protein = 13m,
                            QuantityInStock = 80m,
                            Unit = "chục"
                        },
                        new
                        {
                            Id = 22,
                            Calories = 61m,
                            Carbs = 4.8m,
                            Category = "Trứng & Sữa",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 3.3m,
                            IsAvailable = true,
                            Keywords = "sữa, milk, sữa tươi",
                            Name = "Sữa tươi",
                            Price = 32000m,
                            Protein = 3.2m,
                            QuantityInStock = 100m,
                            Unit = "lít"
                        },
                        new
                        {
                            Id = 23,
                            Calories = 313m,
                            Carbs = 1m,
                            Category = "Trứng & Sữa",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 26m,
                            IsAvailable = true,
                            Keywords = "phô mai, cheese",
                            Name = "Phô mai",
                            Price = 28000m,
                            Protein = 18m,
                            QuantityInStock = 60m,
                            Unit = "hộp"
                        },
                        new
                        {
                            Id = 24,
                            Calories = 89m,
                            Carbs = 23m,
                            Category = "Trái cây",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 0.3m,
                            IsAvailable = true,
                            Keywords = "chuối, banana",
                            Name = "Chuối già 1kg",
                            Price = 25000m,
                            Protein = 1.1m,
                            QuantityInStock = 100m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 25,
                            Calories = 52m,
                            Carbs = 14m,
                            Category = "Trái cây",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Fat = 0.2m,
                            IsAvailable = true,
                            Keywords = "táo, apple",
                            Name = "Táo Fuji 1kg",
                            Price = 60000m,
                            Protein = 0.3m,
                            QuantityInStock = 50m,
                            Unit = "kg"
                        });
                });

            modelBuilder.Entity("MealPlannerAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MealPlannerAPI.Models.ChatHistory", b =>
                {
                    b.HasOne("MealPlannerAPI.Models.MealPlan", "MealPlan")
                        .WithMany()
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MealPlannerAPI.Models.User", "User")
                        .WithMany("ChatHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlannerAPI.Models.HealthProfile", b =>
                {
                    b.HasOne("MealPlannerAPI.Models.User", "User")
                        .WithOne("HealthProfile")
                        .HasForeignKey("MealPlannerAPI.Models.HealthProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlannerAPI.Models.Meal", b =>
                {
                    b.HasOne("MealPlannerAPI.Models.MealPlan", "MealPlan")
                        .WithMany("Meals")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("MealPlannerAPI.Models.MealPlan", b =>
                {
                    b.HasOne("MealPlannerAPI.Models.User", "User")
                        .WithMany("MealPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlannerAPI.Models.MealPlanIngredient", b =>
                {
                    b.HasOne("MealPlannerAPI.Models.Meal", "Meal")
                        .WithMany("Ingredients")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlannerAPI.Models.Product", "Product")
                        .WithMany("MealPlanIngredients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Meal");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MealPlannerAPI.Models.Order", b =>
                {
                    b.HasOne("MealPlannerAPI.Models.MealPlan", "MealPlan")
                        .WithMany()
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MealPlannerAPI.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlannerAPI.Models.OrderItem", b =>
                {
                    b.HasOne("MealPlannerAPI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlannerAPI.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MealPlannerAPI.Models.Meal", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("MealPlannerAPI.Models.MealPlan", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("MealPlannerAPI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MealPlannerAPI.Models.Product", b =>
                {
                    b.Navigation("MealPlanIngredients");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MealPlannerAPI.Models.User", b =>
                {
                    b.Navigation("ChatHistories");

                    b.Navigation("HealthProfile");

                    b.Navigation("MealPlans");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
